% keys.project_versions={''};
% keys.project_version='20180222';
keys.filelist_formatted={};

keys.plot.single_cells                  =1;         % perform single cell plotting

keys.cal.process_spikes                  =1;      % you can choose not to run spikes at all           
keys.cal.process_sites                   =0;      % you can choose not to run lfp sites at all (saving processing time)             
keys.cal.process_by_block                =0;      % you can choose not to run by block (body signals f.e.) at all (saving processing time)        


keys.condition_parameters={'choice'};

%% to check carefully
keys.position_and_plotting_arrangements         ={'options'};

%% computation settings
keys.cal.effectors                  =[0];
keys.cal.reach_hand                 =[0];
keys.cal.types                      =[2,3];
keys.cal.min_trials_per_condition       =4;       
keys.cal.min_trials_in       =4;      
keys.cal.min_trials_ch       =24;                      

%keys.cal.stablity                   =[0.5,1];                     % not assigning sorting table information if criterion is not met. Therefore only excludes when taking only units in the table
keys.cal.stablity                       =[1];                     % not assigning sorting table information if criterion is not met. Therefore only excludes when taking only units in the table
keys.cal.single_rating              =[1,2,3];                   % not assigning sorting table information if criterion is not met. Therefore only excludes when taking only units in the tabl
keys.cal.SNR_rating                 =[1,2,3];                   % not assigning sorting table information if criterion is not met. Therefore only excludes when taking only units in the tabl
keys.cal.datasets                   =[];
keys.cal.remove_trials_without_spikes    =0;

%% batching
keys.batching.combine_monkeys       =1;
keys.batching.targets               ={'dPulv'};
keys.batching.monkeys               ={'Curius','Linus'};
keys.Curius.date                    ='[20150515 20150814]';
keys.Linus.date                     ='[20150508 20151030]';
keys.Linus.color      =[0 0 255]/255;
keys.Curius.color     =[255 0 0]/255;

% %% cell count settings

keys.tt.choice              =[0,1];
keys.tt.reach_hand          =0;
keys.tt.perturbation        =0;

% keys.tt.perturbations               = 0;
% keys.tt.choices                     = 0;
% keys.tt.hands                       = 0;
keys.tt.IC_for_criterion            = 'in';
keys.tt.type_effectors              ={'Msac','Vsac'};


% keys.cc.hands               =[0];
% keys.cc.choices             =[0];
% keys.cc.factors                 ={'epoch','space'};
% keys.cc.conditions_to_plot      ={'Msac','Vsac'};
% keys.cc.epochsE.Msac        ={'INI', 'Fhol','Cue','Cue2','MemE','MemL','PreS','PeriS','TIhol','Thol'}';
% keys.cc.epochsS.Msac        ={'Cue','Cue2','MemE','MemL','PreS','PeriS','TIhol'}';

%% for cell counts in general, but could also be used for PSTH!?
% keys.tt.epoch_criterion             ='SxE or epoch only';
% keys.tt.space_criterion             ='interaction or space only';

%% epochs
keys.EPOCHS_PER_TYPE{2}={...
    'INI',      2,	-0.4,	-0.1,   'INI';...
    'Fhol',     4,	-0.3,	0,      'INI';...
    'Cue',      4,	0.06,	0.16,   'INI';... %% 'Cue',      4,	0.07,	0.17,   'INI';... SHIFTED
    'CueG',     4,	0.04,	0.14,   'INI';...
    'PreS',     60,	-0.1,	-0.01,  'INI';...
    'PeriS',    60,	-0.01,  0.05,   'INI';...
    'Tacq',     5,	0,      0.1,    'INI';...
    'TholG',    5,	0,      0.15,   'INI';...
    'Thol',     20,	-0.3,	0,      'INI';...
    };

keys.ANOVAS_PER_TYPE(2).epoch={'INI' 'Facq';...
    'INI' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'CueG';...
    'Fhol' 'PreS';...
    'Fhol' 'PeriS';...
    'Fhol' 'Tacq';...
    'Fhol' 'TholG';...
    'Fhol' 'Thol'};

keys.WINDOWS_PER_TYPE{2}={...
    'Visual onset', 4,	-0.7,   0.8;...
    'Saccade',      60,	-0.8,  0.7;...
    };

keys.ANOVAS_PER_TYPE(2).hemifield          ={'Fhol','Cue','CueG','PreS','PeriS','Tacq','Thol','TholG'}';
keys.ANOVAS_PER_TYPE(2).positions          ={'Fhol','Cue','CueG','PreS','PeriS','Tacq','Thol','TholG'}';
keys.ANOVAS_PER_TYPE(2).hands              ={'Fhol','Cue','CueG','PreS','PeriS','Tacq','Thol','TholG'}';
keys.ANOVAS_PER_TYPE(2).SxH                ={'Fhol','Cue','CueG','PreS','PeriS','Tacq','Thol','TholG'}';
keys.ANOVAS_PER_TYPE(2).main               ={'INI','Fhol','Cue','PreS','PeriS','Tacq','Thol','TholG'}';

keys.EPOCHS_PER_TYPE{3}={...
    'INI',      2,	-0.4,	-0.1,   'INI';...
    'Fhol',     6,	-0.3,	0,      'INI';...
    'Cue',      6,	0.06,   0.16,   'INI';... %% 'Cue',      4,	0.07,	0.17,   'INI';... SHIFTED
    'CueG',     6,	0.04,   0.14,   'INI';...
    'MemE',     7,	0.07,   0.17,   'INI';... 
    'MemL',     9,	-0.3, 	-0,     'INI';... 
    'PreS',     60,	-0.1, 	-0.01,  'INI';...
    'Pre2',     60,	-0.1, 	-0.01,  'INI';...
    'PreG',     60,	-0.13,  -0.03,  'INI';... %'PreG',     9,	0.04,   0.14,   'INI';...
    'PeriS',	60,	-0.01,  0.05,   'INI';...
    'Peri2',	60,	-0.01,  0.05,   'INI';...
    'TIhol',	10,	0,      0.15,   'INI';...
    'TIholG',	10,	0,      0.15,   'INI';...
    'Tons',     4,	0.02,   0.12,   'INI';...
    'Thol',     5,	0.2,    0.5,    'INI';...
    };

keys.WINDOWS_PER_TYPE{3}={...
    'Cue',          6,	-0.6,   0.78;...
    'Saccade',      60,	-0.7,   0.8;...
    'Go',           9,	-0.2,   0.3;...
    'Target',       4,	-0.2,   0.7;...
    };

keys.ANOVAS_PER_TYPE(3).epoch={'INI' 'Fhol';...
    'Fhol' 'Cue';...
    'Fhol' 'CueG';...
    'Fhol' 'MemE';...
    'Fhol' 'MemL';...
    'MemL' 'PreS';...
    'Fhol' 'Pre2';...
    'Fhol' 'PreG';...
    'MemL' 'PeriS';...
    'Fhol' 'Peri2';...
    'MemL' 'TIhol';...
    'Fhol' 'TIholG';...
    'MemL' 'Tons';...
    'MemL' 'Thol';...
    };

keys.ANOVAS_PER_TYPE(3).hemifield          ={'Fhol','Cue','CueG','MemE','MemL','PreS','Pre2','PreG','PeriS','Peri2','TIhol','TIholG','Tons','Thol'}';
keys.ANOVAS_PER_TYPE(3).positions          ={'Fhol','Cue','CueG','MemE','MemL','PreS','Pre2','PreG','PeriS','Peri2','TIhol','TIholG','Tons','Thol'}';
keys.ANOVAS_PER_TYPE(3).hands              ={'Fhol','Cue','CueG','MemE','MemL','PreS','Pre2','PreG','PeriS','Peri2','TIhol','TIholG','Tons','Thol'}';
keys.ANOVAS_PER_TYPE(3).SxH                ={'Fhol','Cue','CueG','MemE','MemL','PreS','Pre2','PreG','PeriS','Peri2','TIhol','TIholG','Tons','Thol'}';
keys.ANOVAS_PER_TYPE(3).main               ={'INI','Fhol','Cue','MemE','MemL','PreS','PeriS','TIhol','Tons','TIhol','TIholG','Thol'}'; %% 'TIhol' wasnt there??


% multicomparison part
FN=fieldnames(keys.ANOVAS_PER_TYPE);
for f=1:numel(FN)
keys.AN.multicomp_epochs(2).(FN{f})={'Cue','PreS','PeriS','Thol'}';
keys.AN.multicomp_epochs(3).(FN{f})={'Cue','MemL','PreS','PeriS','TIhol'}';
end
keys.AN.multicomp_epochs(2).prefH={''}';
keys.AN.multicomp_epochs(2).angle={''}';
keys.AN.multicomp_epochs(2).distance={''}';
keys.AN.multicomp_epochs(2).DxA={''}';
keys.AN.multicomp_epochs(3).prefH={''}';
keys.AN.multicomp_epochs(3).angle={''}';
keys.AN.multicomp_epochs(3).distance={''}';
keys.AN.multicomp_epochs(3).DxA={''}';
keys.AN.multicomparison='FDR';

